version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      actions-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: npm
    directories:
      - /interop/**/*
    schedule:
      interval: weekly
      day: monday
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      major:
        patterns: ["*"]
        update-types: ["major"]
